name: PHP Composer Test and tag

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-tag:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run psr-12 test
      run: composer run-script test-psr

    - name: Bump version and push tag
      id: tag-action
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: major,minor,patch

    - run: echo "${{ steps.tag-action.outputs.version }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag-action.outputs.new_tag }}
        release_name: Release ${{ steps.tag-action.outputs.new_tag }}
        body: |
          ${{ steps.tag-action.outputs.changelog }}
        draft: false
        prerelease: false
